name: CI

on: [push, pull_request]

env:
  DATABASE_URL: "https://fake.com"
  NEXTAUTH_SECRET: "Required"
  NEXTAUTH_URL: "https://localhost:3000"
  GITHUB_CLIENT_ID: "Required"
  GITHUB_CLIENT_SECRET: "Required"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

        # uses: actions/setup-node@v2
        # with:
        #   node-version: "16.x"

      - name: Install dependencies
        run: npm install . # ci

      - name: TypeCheck
        run: npm run typecheck

      - name: Lint
        run: npm run lint

      # - name: Build and test
      #   run: |
      #     npm run build
      #     npm run typecheck
      #     npm run lint
